name: Trigger Webhook on Prod Push

on:
  pull_request:
    branches:
      - prod
    types:
      - closed

  push:
    branches:
      - prod

jobs:
  push_to_prod:
    if: |
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'prod') || 
      (github.event_name == 'push' && github.ref == 'refs/heads/prod')
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Send webhook to server
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" -X POST "https://github.jce.ac/webhook/f7637a3c-8a24-4be3-bcd8-c2f542a84989")
          if [ $response -ne 200 ]; then
            echo "Webhook call failed with status $response"
            exit 1
          else
            echo "Webhook call succeeded with status $response"
          fi
